'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Movie', [
      {title: 'batman', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://www.greenscene.co.id/wp-content/uploads/2020/09/batman-mati.jpg', rating: '7', year: 2021,genreId: '1', authorId: '1',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'iron man', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg', rating: '7', year: 2021,genreId: '1', authorId: '1',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'iron man 2', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://images.tokopedia.net/img/cache/700/product-1/2020/2/8/batch-upload/batch-upload_3314c8c8-6cc4-4b27-98f0-e797b7272dfc.jpg', rating: '7', year: 2021,genreId: '1', authorId: '1',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'iron man 3', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://upload.wikimedia.org/wikipedia/id/d/d5/Iron_Man_3_theatrical_poster.jpg', rating: '7', year: 2021,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'spiderman', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Spider-Man2002Poster.jpg/220px-Spider-Man2002Poster.jpg', rating: '7', year: 2021,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'spiderman 2', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/M/MV5BMzY2ODk4NmUtOTVmNi00ZTdkLTlmOWYtMmE2OWVhNTU2OTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg', rating: '7', year: 2021,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'spiderman 3', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/M/MV5BYTk3MDljOWQtNGI2My00OTEzLTlhYjQtOTQ4ODM2MzUwY2IwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_FMjpg_UX1000_.jpg', rating: '7', year: 2019,genreId: '1', authorId: '3',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'amazing spider man', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://upload.wikimedia.org/wikipedia/en/0/02/The_Amazing_Spider-Man_theatrical_poster.jpeg', rating: '7', year: 2020,genreId: '1', authorId: '3',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'amazing spider man 2', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://cdn.idntimes.com/content-images/post/20200615/5413064-so-7a50664ef437c43d2c7479d2dc786c67.jpg', rating: '7', year: 2020,genreId: '1', authorId: '3',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'spider far from home', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://statik.tempo.co/data/2019/05/07/id_839936/839936_720.jpg', rating: '7', year: 2020,genreId: '1', authorId: '4',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'spider no way home', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://pict-a.sindonews.net/dyn/620/pena/news/2021/09/01/700/527998/5-kostum-spiderman-untuk-peter-parker-di-no-way-home-ist.jpg', rating: '7', year: 2020,genreId: '1', authorId: '4',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'joker', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/I/81YdUDaMiWL._AC_SY679_.jpg', rating: '7', year: 2021,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'superman', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://cdn1-production-images-kly.akamaized.net/MvYu8uAc4QtsUv8bWFvsHfGcLVw=/640x640/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/725423/original/superman_in_batman_v_superman_dawn_of_justice-1600x900.jpg', rating: '7', year: 2019,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'thor', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/I/51Ower3oGQL._SY445_.jpg', rating: '7', year: 2019,genreId: '1', authorId: '3',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'thor 2', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/I/91SZB93YMAL._SL1500_.jpg', rating: '7', year: 2019,genreId: '1', authorId: '3',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'Final fantasy 7', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/M/MV5BNTk4NjBhZTUtN2MwMy00MzIyLWFhN2ItMmUwYzQ4MWQxODM3L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_.jpg', rating: '7', year: 2020,genreId: '1', authorId: '3',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: 'final fantasy xv', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/M/MV5BOTEwNzMxNTU5M15BMl5BanBnXkFtZTgwMzMyMjg3OTE@._V1_.jpg', rating: '7', year: 2018,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: '3 A.M', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/M/MV5BZWRhYTMzMDgtZGFiZS00ZTc0LTk2NzItZjNkZjAxMjQwNWNhXkEyXkFqcGdeQXVyMjQxMDgxMjg@._V1_.jpg', rating: '7', year: 2018,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date},
      {title: '23:59', synopsis: 'test content uji percobaan', trailerUrl: 'youtube', imgUrl: 'https://m.media-amazon.com/images/M/MV5BMzM0N2RkYzQtZmNhOC00NTFlLTk2OGYtMmZmZmExM2QwOTYxXkEyXkFqcGdeQXVyODk2MDI0NTc@._V1_.jpg', rating: '7', year: 2018,genreId: '1', authorId: '2',status: 'active',createdAt: new Date, updatedAt: new Date}
    ], {})
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Movie', null, {})
  }
};
